---
 
- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: cisco_ios
  connection: local
  gather_facts: False
 
  tasks:
    - name: TEST TEMPLATE
      ntc_show_command:
        connection: ssh                   
        platform: cisco_ios                
        use_templates: false
        command: "show ver"   
        host: "{{ inventory_hostname }}"  
        username: "{{ username }}"
        password: "{{ password }}"
      register: results

    - debug: var=results.response
